name: acamae-backend

services:
  db:
    image: mariadb:11
    restart: always
    healthcheck:
      test:
        [
          'CMD',
          'mariadb',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p${MYSQL_ROOT_PASSWORD}',
          '-e',
          'SELECT 1;',
        ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 60s
    env_file:
      - ../.env.${NODE_ENV:-development}
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-gestion_esports}
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - acamae-network

  nginx:
    build:
      context: ./nginx
    container_name: acamae-nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    env_file:
      - ../.env.${NODE_ENV:-development}
    depends_on:
      - backend
      - phpmyadmin
    networks:
      - acamae-network

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    command: >
      sh -c "npm run prisma:deploy && npm run start:dev"
    stdin_open: true
    tty: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - ../.env.${NODE_ENV:-development}
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    ports:
      - '9229:9229' # inspector (solo usado en modo debug)
    expose:
      - '4000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acamae-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - ../.env.${NODE_ENV:-development}
    environment:
      - PMA_HOST=db
    expose:
      - '80'
    ports:
      - '8080:80'
    volumes:
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acamae-network

networks:
  acamae-network:
    external: true

volumes:
  mariadb_data:
