services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ../.env.development
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  nginx:
    build:
      context: ./nginx
    container_name: emanager.com-nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - phpmyadmin

  backend:
    build:
      context: ../
    stdin_open: true
    tty: true
    env_file:
      - ../.env.development
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
      - ../tsconfig.json:/app/tsconfig.json
    expose:
      - '3000'
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    expose:
      - '80'
    volumes:
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  mariadb_data:
