name: acamae-backend

# Variables de entorno globales
x-environment: &environment
  NODE_ENV: ${NODE_ENV:-development}

services:
  db:
    image: mariadb:11
    restart: always
    healthcheck:
      test:
        [
          'CMD',
          'mariadb',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p${MYSQL_ROOT_PASSWORD}',
          '-e',
          'SELECT 1;',
        ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 60s
    env_file:
      - ../.env.${NODE_ENV:-development}
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-gestion_esports}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - acamae-network

  nginx:
    build:
      context: ./nginx
    container_name: acamae-nginx
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    env_file:
      - ../.env.${NODE_ENV:-development}
    depends_on:
      - backend
      - phpmyadmin
    networks:
      - acamae-network

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-4000}
    command: >
      sh -c "npx prisma migrate deploy && npx prisma db seed && npm run build:timezones && node src/index.js"
    stdin_open: true
    tty: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - ../.env.${NODE_ENV:-development}
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    ports:
      - '9229:9229' # inspector (solo usado en modo debug)
    expose:
      - '${PORT}'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acamae-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PMA_HOST: db
    expose:
      - '80'
    ports:
      - '8080:80'
    volumes:
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acamae-network

networks:
  acamae-network:
    external: true

volumes:
  mariadb_data:
    driver: local
