services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ../.env.production
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    networks:
      - acamae-network

  nginx:
    build:
      context: ./nginx
    container_name: acamae-nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    env_file:
      - ../.env.production
    depends_on:
      - backend
      - phpmyadmin
    networks:
      - acamae-network

  backend:
    build:
      context: ../
    command: ['npm', 'run', 'start:prod']
    stdin_open: true
    tty: true
    env_file:
      - ../.env.production
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    expose:
      - '${PORT:-4000}'
    depends_on:
      - db
    networks:
      - acamae-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - ../.env.production
    environment:
      - PMA_HOST=db
    expose:
      - '80'
    volumes:
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - acamae-network

networks:
  acamae-network:
    driver: bridge

volumes:
  mariadb_data:
