services:
  db:
    image: mariadb
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD']
      interval: 5s
      retries: 10
      timeout: 3s
    env_file:
      - ../.env.development
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    networks:
      - acamae-network

  nginx:
    build:
      context: ./nginx
    container_name: acamae-nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    env_file:
      - ../.env.development
    depends_on:
      - backend
      - phpmyadmin
    networks:
      - acamae-network

  backend:
    build:
      context: ../
    command: >
      sh -c "npx prisma migrate deploy && npm run start:${START_MODE:-dev}"
    stdin_open: true
    tty: true
    env_file:
      - ../.env.${NODE_ENV:-development}
    environment:
      - START_MODE=${START_MODE:-dev}
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    ports:
      - '9229:9229' # inspector (solo usado en modo debug)
    expose:
      - '${PORT:-4000}'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acamae-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - ../.env.development
    environment:
      - PMA_HOST=db
    expose:
      - '80'
    volumes:
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - acamae-network

networks:
  acamae-network:
    external: true

volumes:
  mariadb_data:
