# @description: Este workflow se encarga de la integración continua
# @triggers: Pull requests a main
# @permissions: read-only para contenido y paquetes
name: CI
run-name: 'CI: ${{ github.event.pull_request.title }}'

on:
  pull_request:
    branches: [main, release]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-all:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4
      - name: Install GNU coreutils (for sha256sum)
        if: runner.os == 'macOS'
        run: brew install coreutils

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
          setup-git-identity: true

      # LINT
      - run: npm run lint:fix
      - run: npm run lint

      # Build timezones catalog (keeps /api/timezones up-to-date)
      - name: Build timezones catalog
        run: npm run build:timezones

      # SONARQUBE CACHE
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # SONARQUBE SCAN
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    permissions:
      contents: read
      packages: read
      pull-requests: read
